style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/michenriksen/hugo-theme-til
options:
  commits:
    filters:
      Type:
        - docs
        - feat
        - fix
  commit_groups:
    title_maps:
      docs: Documentation
      feat: Features
      fix: Fixes
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
